/**
 * Writes `src/lib/erie-canal.ts` from the Erie Canal in OpenStreetMap. Run it
 * again when the canal's line in OpenStreetMap is corrected:
 *
 *   bun scripts/erie-canal.ts
 */
import { writeFileSync } from 'node:fs';
import { COUNTY_VIEW_BOX, project } from '../src/lib/municipalities';

/** Every canal way named "Erie Canal" in a box a little wider than the county. */
const QUERY =
  '[out:json][timeout:90];' +
  'way["waterway"="canal"]["name"="Erie Canal"](42.93,-78.1,43.37,-77.3);' +
  'out geom;';

/**
 * How far, in map units, a simplified edge may stray from the canal. A town
 * drawn on its own is about 150 units wide, so this is well under a pixel.
 */
const TOLERANCE = 0.2;

type Point = [number, number];

/** Douglas–Peucker, keeping both ends of the run. */
function simplify(points: Point[]): Point[] {
  if (points.length < 3) return points;
  const [ax, ay] = points[0];
  const [bx, by] = points[points.length - 1];
  const length = Math.hypot(bx - ax, by - ay);
  let far = 0;
  let index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const [px, py] = points[i];
    const distance =
      length === 0
        ? Math.hypot(px - ax, py - ay)
        : Math.abs((bx - ax) * (ay - py) - (ax - px) * (by - ay)) / length;
    if (distance > far) {
      far = distance;
      index = i;
    }
  }
  if (far <= TOLERANCE) return [points[0], points[points.length - 1]];
  return [
    ...simplify(points.slice(0, index + 1)).slice(0, -1),
    ...simplify(points.slice(index)),
  ];
}

const response = await fetch('https://overpass-api.de/api/interpreter', {
  method: 'POST',
  // Overpass refuses a request with no user agent of its own.
  headers: {
    'User-Agent': 'rochester-parks (github.com/markgoho/rochester-parks)',
  },
  body: new URLSearchParams({ data: QUERY }),
});
if (!response.ok) throw new Error(`Overpass: ${response.status}`);
const { elements } = (await response.json()) as {
  elements: {
    nodes: number[];
    geometry: { lat: number; lon: number }[];
  }[];
};

/**
 * OpenStreetMap cuts the canal into many ways at locks and bridges, each
 * drawn in whichever direction its mapper chose. Start at the west end and
 * join each next way at the node it shares with the line so far.
 */
const ways = elements
  .filter((w) => w.nodes[0] !== w.nodes[w.nodes.length - 1])
  .map((w) => ({
    first: w.nodes[0],
    last: w.nodes[w.nodes.length - 1],
    points: w.geometry.map(({ lat, lon }) => {
      const { x, y } = project(lat, lon);
      return [x, y] as Point;
    }),
  }));
const ends = ways.flatMap((w) => [w.first, w.last]);
const loose = (node: number) => ends.filter((n) => n === node).length === 1;
const west = ways
  .flatMap((w) => [
    { way: w, node: w.first, point: w.points[0] },
    { way: w, node: w.last, point: w.points[w.points.length - 1] },
  ])
  .filter((end) => loose(end.node))
  .sort((a, b) => a.point[0] - b.point[0])[0];

let line: Point[] = [];
let node = west.node;
const left = new Set(ways);
for (let way = west.way; way; ) {
  left.delete(way);
  const forward = way.first === node;
  const points = forward ? way.points : [...way.points].reverse();
  line = line.concat(line.length ? points.slice(1) : points);
  node = forward ? way.last : way.first;
  way = [...left].find((w) => w.first === node || w.last === node)!;
}
if (left.size) throw new Error(`${left.size} canal ways did not join the line`);

/** Cut the line where it leaves the sides of the map, so it ends at the edge. */
const [, , width] = COUNTY_VIEW_BOX.split(' ').map(Number);
const inside: Point[] = [];
line.forEach(([x, y], i) => {
  const [px, py] = line[i - 1] ?? [x, y];
  for (const edge of [0, width]) {
    if ((px - edge) * (x - edge) < 0) {
      inside.push([edge, py + ((y - py) * (edge - px)) / (x - px)]);
    }
  }
  if (x >= 0 && x <= width) inside.push([x, y]);
});

const round = (n: number) => Number(n.toFixed(2));
const path =
  'M' +
  simplify(inside)
    .map(([x, y]) => `${round(x)} ${round(y)}`)
    .join('L');

writeFileSync(
  'src/lib/erie-canal.ts',
  `// Generated by scripts/erie-canal.ts from the Erie Canal in OpenStreetMap.
// Do not edit by hand.

/** The canal's centre line across the county, in the county map's space. */
export const ERIE_CANAL =
  '${path}';
`
);
console.log(`${line.length} points, ${inside.length} on the map`);
