/**
 * Writes `src/lib/neighborhood-outlines.ts` from the City of Rochester's own
 * neighborhood layer. Run it again when the city redraws a boundary:
 *
 *   bun scripts/neighborhoods.ts
 */
import { writeFileSync } from 'node:fs';
import { project, type Outline } from '../src/lib/municipalities';

const SOURCE =
  'https://maps.cityofrochester.gov/server/rest/services/ProjectsAndPlans/Neighborhoods/FeatureServer/0/query' +
  '?where=1%3D1&outFields=Name&outSR=4326&geometryPrecision=6&f=geojson';

/**
 * How far, in map units, a simplified edge may stray from the city's line.
 * The whole city is about 170 units wide, so this is well under a pixel.
 */
const TOLERANCE = 0.05;

/**
 * The layer names each area after its neighborhood association, in capitals.
 * These are the names a reader knows it by. A name not listed is title-cased.
 */
const NAMES: Record<string, string> = {
  '14621': '14621',
  '19TH WARD': '19th Ward',
  'ABC STREETS': 'ABC Streets',
  'B.E.S.T.': 'BEST',
  CONEA: 'CONEA',
  'CENTRAL BUSINESS DISTRICT': 'Downtown',
  'EMMA, ACE': 'EMMA and ACE',
  'MAYORS HEIGHTS': "Mayor's Heights",
  'N. MARKETVIEW HEIGHTS': 'North Marketview Heights',
  NEMNU: 'NEMNU',
  'NEIGHBORHOOD OF THE ARTS': 'Neighborhood of the Arts',
  'P.O.D.': 'People of Dutchtown',
  'S. MARKETVIEW HEIGHTS': 'South Marketview Heights',
  SOUTHWEDGE: 'South Wedge',
  'U of R': 'University of Rochester',
  'WESTSIDE NEIGHBORHOOD ASSOCIATION': 'Westside',
};

type Point = [number, number];

/** Douglas–Peucker, keeping both ends of the run. */
function simplify(points: Point[]): Point[] {
  if (points.length < 3) return points;
  const [ax, ay] = points[0];
  const [bx, by] = points[points.length - 1];
  const length = Math.hypot(bx - ax, by - ay);
  let far = 0;
  let index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const [px, py] = points[i];
    const distance =
      length === 0
        ? Math.hypot(px - ax, py - ay)
        : Math.abs((bx - ax) * (ay - py) - (ax - px) * (by - ay)) / length;
    if (distance > far) {
      far = distance;
      index = i;
    }
  }
  if (far <= TOLERANCE) return [points[0], points[points.length - 1]];
  return [
    ...simplify(points.slice(0, index + 1)).slice(0, -1),
    ...simplify(points.slice(index)),
  ];
}

function nameOf(raw: string): string {
  return (
    NAMES[raw] ??
    raw.toLowerCase().replace(/\b[a-z]/g, (letter) => letter.toUpperCase())
  );
}

function keyOf(name: string): string {
  return name
    .toLowerCase()
    .replace(/'/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** A ring in map units, closed by `Z` rather than by a repeated point. */
function pathOf(ring: number[][]): string {
  const points = simplify(
    ring.map(([longitude, latitude]) => {
      const { x, y } = project(latitude, longitude);
      return [x, y] as Point;
    })
  ).slice(0, -1);
  const round = (n: number) => Number(n.toFixed(2));
  return (
    'M' + points.map(([x, y]) => `${round(x)} ${round(y)}`).join('L') + 'Z'
  );
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE}: ${response.status}`);
const { features } = (await response.json()) as {
  features: {
    properties: { Name: string };
    geometry: { type: string; coordinates: number[][][] | number[][][][] };
  }[];
};

/** Two areas carry a second, separate piece under the same name. */
const byName = new Map<string, Outline>();
for (const { properties, geometry } of features) {
  const name = nameOf(properties.Name);
  const polygons = (
    geometry.type === 'MultiPolygon'
      ? geometry.coordinates
      : [geometry.coordinates]
  ) as number[][][][];
  const shape = byName.get(name) ?? { key: keyOf(name), name, paths: [] };
  // Only the outer ring: no neighborhood in the layer has a hole.
  for (const polygon of polygons) shape.paths.push(pathOf(polygon[0]));
  byName.set(name, shape);
}

const outlines = [...byName.values()].sort((a, b) =>
  a.name.localeCompare(b.name)
);

writeFileSync(
  'src/lib/neighborhood-outlines.ts',
  `// Generated by scripts/neighborhoods.ts from the City of Rochester's
// neighborhood layer. Do not edit by hand.
import type { Outline } from './municipalities';

export const NEIGHBORHOOD_OUTLINES: Outline[] = ${JSON.stringify(outlines, null, 2)};
`
);
console.log(`${outlines.length} neighborhoods`);
