/**
 * Writes `src/lib/waterways.ts` from the Erie Canal and the Genesee River in
 * OpenStreetMap. Run it again when either line in OpenStreetMap is corrected:
 *
 *   bun scripts/waterways.ts
 */
import { writeFileSync } from 'node:fs';
import { COUNTY_VIEW_BOX, project } from '../src/lib/municipalities';
import { waterIn } from '../src/lib/water';

/** Each waterway, found by its OpenStreetMap tag and name. */
const WATERWAYS = [
  {
    constant: 'ERIE_CANAL',
    doc: "The canal's centre line across the county",
    waterway: 'canal',
    name: 'Erie Canal',
  },
  {
    constant: 'GENESEE_RIVER',
    doc: "The river's centre line from the county's south edge to the lake",
    waterway: 'river',
    name: 'Genesee River',
  },
];

/**
 * How far, in map units, a simplified edge may stray from the water. A town
 * drawn on its own is about 150 units wide, so this is well under a pixel.
 */
const TOLERANCE = 0.2;

type Point = [number, number];

/** Douglas–Peucker, keeping both ends of the run. */
function simplify(points: Point[]): Point[] {
  if (points.length < 3) return points;
  const [ax, ay] = points[0];
  const [bx, by] = points[points.length - 1];
  const length = Math.hypot(bx - ax, by - ay);
  let far = 0;
  let index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const [px, py] = points[i];
    const distance =
      length === 0
        ? Math.hypot(px - ax, py - ay)
        : Math.abs((bx - ax) * (ay - py) - (ax - px) * (by - ay)) / length;
    if (distance > far) {
      far = distance;
      index = i;
    }
  }
  if (far <= TOLERANCE) return [points[0], points[points.length - 1]];
  return [
    ...simplify(points.slice(0, index + 1)).slice(0, -1),
    ...simplify(points.slice(index)),
  ];
}

/** Every way of one waterway in a box a little wider than the county. */
const query = (waterway: string, name: string) =>
  '[out:json][timeout:90];' +
  `way["waterway"="${waterway}"]["name"="${name}"](42.93,-78.1,43.37,-77.3);` +
  'out geom;';

async function line(waterway: string, name: string): Promise<Point[]> {
  const response = await fetch('https://overpass-api.de/api/interpreter', {
    method: 'POST',
    // Overpass refuses a request with no user agent of its own.
    headers: {
      'User-Agent': 'rochester-parks (github.com/markgoho/rochester-parks)',
    },
    body: new URLSearchParams({ data: query(waterway, name) }),
  });
  if (!response.ok) throw new Error(`Overpass: ${response.status}`);
  const { elements } = (await response.json()) as {
    elements: {
      nodes: number[];
      geometry: { lat: number; lon: number }[];
    }[];
  };

  /**
   * OpenStreetMap cuts a waterway into many ways at locks and bridges, each
   * drawn in whichever direction its mapper chose. Start at the loose end
   * furthest to the south-west, the canal's west end and the river's source
   * end. The map's y grows downward, so that end has the least x − y. Join
   * each next way at the node it shares with the line so far.
   */
  const ways = elements
    .filter((w) => w.nodes[0] !== w.nodes[w.nodes.length - 1])
    .map((w) => ({
      first: w.nodes[0],
      last: w.nodes[w.nodes.length - 1],
      points: w.geometry.map(({ lat, lon }) => {
        const { x, y } = project(lat, lon);
        return [x, y] as Point;
      }),
    }));
  const ends = ways.flatMap((w) => [w.first, w.last]);
  const loose = (node: number) => ends.filter((n) => n === node).length === 1;
  const start = ways
    .flatMap((w) => [
      { way: w, node: w.first, point: w.points[0] },
      { way: w, node: w.last, point: w.points[w.points.length - 1] },
    ])
    .filter((end) => loose(end.node))
    .sort((a, b) => a.point[0] - a.point[1] - (b.point[0] - b.point[1]))[0];

  let line: Point[] = [];
  let node = start.node;
  const left = new Set(ways);
  for (let way = start.way; way; ) {
    left.delete(way);
    const forward = way.first === node;
    const points = forward ? way.points : [...way.points].reverse();
    line = line.concat(line.length ? points.slice(1) : points);
    node = forward ? way.last : way.first;
    way = [...left].find((w) => w.first === node || w.last === node)!;
  }
  if (left.size) throw new Error(`${left.size} ${name} ways did not join`);
  return line;
}

const round = (n: number) => Number(n.toFixed(2));
const [x, y, width, height] = COUNTY_VIEW_BOX.split(' ').map(Number);

let out = `// Generated by scripts/waterways.ts from OpenStreetMap. Do not edit by hand.
`;
for (const { constant, doc, waterway, name } of WATERWAYS) {
  const points = await line(waterway, name);
  const path =
    'M' +
    simplify(points)
      .map(([px, py]) => `${round(px)} ${round(py)}`)
      .join('L');
  // Cut the line where it leaves the map, so it ends at the edge.
  const d = waterIn(path, { x, y, width, height });
  out += `
/** ${doc}, in the county map's space. */
export const ${constant} =
  '${d}';
`;
  console.log(`${name}: ${points.length} points`);
}
writeFileSync('src/lib/waterways.ts', out);
